name: Update Latest Videos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  youtube-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install googleapis

      - name: Fetch and update videos
        run: |
          node .github/scripts/updateVideos.mjs
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

      - name: Create pull request
        run: |
          BRANCH_NAME="update-videos-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update latest videos"
          git push origin $BRANCH_NAME

          PR_RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "Update latest videos", "head": "'"$BRANCH_NAME"'", "base": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls)

          PR_URL=$(echo $PR_RESPONSE | jq -r '.html_url')

          # Wait for the pull request to be created
          sleep 10s

          # Merge the pull request
          curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method": "squash"}' \
            $PR_URL/merge
