name: Update Latest Videos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  youtube-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install googleapis

      - name: Fetch and update videos
        run: |
          node .github/scripts/updateVideos.mjs
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

      - name: Disable branch protection temporarily
        run: |
          BRANCH_PROTECTION_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            | jq -r '.enabled')

          if [ "$BRANCH_PROTECTION_STATUS" = "true" ]; then
            curl -X DELETE -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/branches/main/protection
          fi

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .

          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Update latest videos"
          fi

      - name: Push changes
        run: |
          git pull origin main
          git push

      - name: Re-enable branch protection
        if: ${{ env.BRANCH_PROTECTION_STATUS == 'true' }}
        run: |
          curl -X PUT -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"required_status_checks": null, "enforce_admins": null, "required_pull_request_reviews": null, "restrictions": null}' \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection
