name: Update Latest Videos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Run every hour

jobs:
  youtube-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install googleapis

      - name: Fetch and update videos
        run: |
          node .github/scripts/updateVideos.mjs
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .

          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Update latest videos"
            git config pull.rebase false  
            git pull origin main
            git push
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update latest videos"
          labels: "auto-update"
          branch: main
          base: main
          body: "This pull request was automatically generated to update the latest videos."
