# name: Update Latest Videos

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 * * * *"

# jobs:
#   youtube-workflow:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Git user identity
#         run: |
#           git config --global user.email "actions@github.com"
#           git config --global user.name "GitHub Actions"

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "16"

#       - name: Install dependencies
#         run: |
#           npm install googleapis

#       - name: Fetch and update videos
#         run: |
#           node .github/scripts/updateVideos.mjs
#         env:
#           YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
#           YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

#       - name: Create a new branch
#         run: |
#           BRANCH_NAME="update-videos-$(date +%s)"
#           git checkout -b $BRANCH_NAME
#           git add .
#           git commit -m "Update latest videos"

#       - name: Push changes to the new branch
#         run: git push origin $BRANCH_NAME

#       - name: Set upstream branch
#         run: git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME

#       - name: Merge changes into main
#         run: |
#           git checkout main
#           git pull origin main
#           git merge --no-ff $BRANCH_NAME -m "Merge $BRANCH_NAME into main"
#           git push origin main

name: Update README with Date and Time

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Last updated at $(date -u)" > README.md

      - name: Commit Changes
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USER_NAME }}"
          git add README.md
          git commit -m "Update README with current date and time [skip ci]"
          git pull --rebase
          git push --force-with-lease "https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git" HEAD:refs/heads/main
